### ISSUE TITLE
rmsgw_aci does not work as expected

### ISSUE THREAD

**Issue by n9seo** [nwdigitalradio/rmsgw#15]
Hi,

I managed to get rmsgw going up on my custom debian buster install.  I did not  use your scripts since it was already running ax25 with many things configured but perhaps rmsgw_aci does not like something.

Most of the configuration was me stumbling through the /etc/rmsgw/ files and guessing, since the docs seemed to not be quite inline with my setup, so some improvisation was done.  

So the gateway works at least, everything builds fine.  But I cannot run the rmsgw_aci.   SO far I am only updating winlink with the 
scripts mentioned here:
https://github.com/nwdigitalradio/rmsgw/blob/master/admin/README.md#test-your-updated-admin-files

When I try to run rmsgw_aci by hand this is what I get:

```
root@debian:/home/n9seo# rmsgw_aci 
port vhf unavailable
port xnet unavailable
{
  "ResponseStatus": {}
}
Response status code: 200
('Debug: Response =', '{"ResponseStatus":{}}')
Debug: Content type: application/json; charset=utf-8
Debug: Good Response status code
('ResponseStatus is NULL: ', {})
```

Here is my axports if that matters:
```
#portname	callsign	speed	paclen	window	description
axip		N9SEO-14		115200	253	4	Linux (AX25<->AXIP)
#axudp		N9SEO-9		115200	253	7	Linux (AX25<->AXUDP)
vhf		N9SEO-6		38400	128	2	145.73Mhz 1200bps(Austin Packet Network)
xrp		N9SEO-12	38400   253	2 	Link to Xrouter
xnet		N9SEO-13	38400	253	2	Link to XNET
#bpsk 		n9seo-3		38400	30	1	Net105(day)|Net40(night) 1300Hz 300bps
#afsk		N9SEO-12	38400	64	1	Net105(day)|Net40(night) 1700Hz 300bps
```

Let me know if you need anything else.

**Comment by n9seo** [comment]
Maybe I got this working?  I guess 200 seems like it works but shrug, cant really tell from the RMS map thing.  Seems like only getting output from these scripts.  Reports the fall back for 'Comments'  instead of the set value in XML.  Assuming that rmsgw_aci reports something else than this from line 158 of updatesysop.py.

 158:        comment.text = 'V5 Services Test: ' + str(datetime.datetime.now())


Does rmsgw_aci want to have sole ownership of the linux ax25 network device?  I dont think it really requires this.
I can connect and send mail to/from winlink so must just be a reporting issue.

**Comment by n7nix** [comment]
I would prefer it you use the groups.io forum for LinuxRMS (https://groups.io/g/LinuxRMS/topics) for this problem because the issue is your configuration and not a bug in rmsgw_aci. Read my response from the previous issue. I need to know that you are running the latest versions of the python scripts.

Which version of rmsgw are you using?

grep -i label /usr/local/etc/rmsgw/.version_info 
Which version of Linux kernel are you running?

uname -a
Do not need to run rmschanstat OR rmsgw_aci as root. Sample outputs follow:

rmschanstat ax25 udr0 N7NIX
channel udr0 with callsign N7NIX on interface ax0 up

rmsgw_aci
channel udr0 with callsign N7NIX-10 on interface ax0 up

Try running chk_wlaci.sh found here: https://github.com/nwdigitalradio/n7nix/blob/master/rmsgw/chk_wlaci.sh
Most likely your AX.25 ports vhf, xnet have not been configured properly.
Run this and post the output

ifconfig | grep AMPR

Delete all the commented out "portnames" in axports.

Please respond to this in the LinuxRMS groups.io forum.

**Comment by n9seo** [comment]
OK will do, I pushed a topic earlier, but was waiting for approval.  Its
really related to that so if someone could approve it, I will carry this
over to there.  Thanks!

-kayne
